### ISSUE TITLE
Models don't exist - please help!

### ISSUE THREAD

**Issue by mattcopas** [j6mes/fever-allennlp#1]
Hi,

When trying to retrieve your models I receive a 404 from nginx:

https://jamesthorne.co.uk/fever/fever-esim-elmo.tar.gz
https://jamesthorne.co.uk/fever/fever-esim.tar.gz 
https://jamesthorne.co.uk/fever/fever-da.tar.gz

Would you be able to fix this please?

Thank you very much

**Comment by dks12345** [comment]
Hi , Are pre trained model uploaded somewhere else?
These links are not working  -  https://jamesthorne.co.uk/fever/*
Can you please help?

Thanks

**Comment by j6mes** [comment]
Fixed
